### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by bikerp** [boylesoftware/tomcat-oidcauth#30] opened 2020-05-22 07:20 UTC
Hi,
I'm wondering how to logout the authenticated user. I tried `request.logout();` but it has no effect.
Any idea how to do it?
Thanks

**Comment by Percyvalmg** [comment] 2020-05-22 10:22
What happens when you go to the /logout endpoint?

**Comment by bikerp** [comment] 2020-05-22 12:24
I get 404

**Comment by Percyvalmg** [comment] 2020-05-22 13:38
Are you using the sample application or are you using your won?

**Comment by bikerp** [comment] 2020-05-22 14:01
I tried the sample apllication. When I click on Logout then Go Back Home and then any of the secured page I'm still logged on

**Comment by levahim** [comment] 2020-08-01 12:28
As mentioned in the sample application (see logout.jsp), logging out from Tomcat session does not automatically log you out from the IdP. If you are not logged out from the IdP, when you request a protected page, Tomcat redirects you to the IdP, which then automatically authenticates you (because you're still logged in there) and immediately redirects you back to the application with the auth tokens. This is expected behavior.

Closing the issue. Please re-open it if I'm missing something.

**Closed by levahim** 2020-08-01 12:28 UTC
